stateDiagram-v2
12: (12) END
11: (11) g = d
11 --> 12
10: (10) d = e - f
10 --> 11
9: (9) d = e + f
9 --> 11
8: (8) if (f > 5)
8 --> 10
8 --> 9
7: (7) f = f + b
7 --> 8
6: (6) f = b + c
6 --> 7
5: (5) e = d + a
5 --> 6
4: (4) c = 1
4 --> 5
3: (3) b = 3
3 --> 4
2: (2) a = 2
2 --> 3
1: (1) d = 1
1 --> 2
0: (0) START
0 --> 1
